---
fullname: Asynchronous Test
shortname: coq-async-test
opam_name: coq-async-test
organization: liyishuai
action: true
ci_test_dependants: true
synopsis: Testing asynchronous system
description: From interaction trees to asynchronous tests.
authors:
  - name: Yishuai Li
    email: liyishuai.lys@alibaba-inc.com
    orcid: 0000-0002-5728-5903
license:
  - fullname: Mozilla Public License 2.0
    identifier: MPL-2.0
dependencies:
  - description: '[Coq JSON](https://github.com/liyishuai/coq-json)'
    opam:
      name: coq-json
      version: '{ >= "0.1.1" }'
  - description: '[ITreeIO](https://github.com/Lysxia/coq-itree-io)'
    opam:
      name: coq-itree-io
      version: '{ >= "0.1.0" }'
  - description: '[QuickChick](https://github.com/QuickChick/QuickChick/)'
    opam:
      name: coq-quickchick
      version: '{ >= "1.6.3" }'
categories:
  - name: Miscellaneous/Extracted Programs/Decision procedures
keywords:
  - name: extraction
  - name: reactive systems
namespace: AsyncTest
publications:
  - pub_title: Testing by Dualization
    pub_url: https://repository.upenn.edu/edissertations/5376
    pub_doi: 10.48550/arXiv.2210.01047
test_target: test
opam-file-maintainer: 'Yishuai Li <liyishuai.lys@alibaba-inc.com>'
supported_coq_versions:
  text: 8.14 or later
  opam: '{ >= "8.14~" }'
tested_coq_opam_versions:
  - version: '8.14'
  - version: '8.15'
  - version: '8.16'
  - version: '8.17'
  - version: 'dev'
action_appendix: |2-
            export: 'OPAMWITHTEST'
          env:
            OPAMWITHTEST: true
